steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://source.developers.google.com/${_PROJECT_ID}/{_REPO_NAME}']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/{_PROJECT_ID}/pyproject:${_VERSION}']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', 'gcr.io/{_PROJECT}/pyproject:${_VERSION}']

  - name: 'gcr.io/cloud-builders/gke-deploy'
    args: 
    - 'apply'
    - '--filename=${_FILE_PATH}'
    - '--location=${_LOCATION}'
    # - '--image=${_IMAGE_NAME}'
    - '--cluster=${_CLUSTER_NAME}'

images:
  - "${_IMAGE_NAME}:${_VERSION}"
substitutions:
   _PROJECT_ID: devops-374608
   _REPO_NAME: github_masudd11_python-project
   _FILE_PATH: pyapp.yaml
   _LOCATION: us-central1-c
   _IMAGE_NAME: gcr.io/devops-374607/pyproject
   _CLUSTER_NAME: python-cluster
   _VERSION: v1.0

options:
    # substitutions_option: 'ALLOW_LOOSE'
    logging: 'CLOUD_LOGGING_ONLY'