steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://source.developers.google.com/p/${_PROJECT}/r/${_REPO_NAME}']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${_PROJECT}/pyproject:${_VERSION}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${_PROJECT}/pyproject:${_VERSION}']

  - name: 'gcr.io/cloud-builders/gke-deploy'
    args: 
    - 'run'
    - '--filename=${_FILE_PATH}'
    - '--location=${_LOCATION}'
    - '--image=${_IMAGE_NAME}'
    - '--cluster=${_CLUSTER_NAME}'

substitutions:
   _PROJECT: kubernetes-gcp-383911
   _REPO_NAME: github_masudd11_python-project
   _FILE_PATH: pyapp.yaml
   _LOCATION: us-central1-b
   _IMAGE_NAME: gcr.io/kubernetes-gcp-383911/pyproject:${_VERSION}
   _CLUSTER_NAME: my-gke-cluster
   _VERSION: $SHORT_SHA

options:
    # substitutions_option: 'ALLOW_LOOSE'
    logging: 'CLOUD_LOGGING_ONLY'